### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by wlrd1000** [MainSilent/hCaptcha-Bypass#2]
C:\Users\rod\Desktop\hCaptcha-Bypass-master>py main.py
Traceback (most recent call last):
  File "C:\Users\rod\Desktop\hCaptcha-Bypass-master\main.py", line 74, in <module>
    print(new())
  File "C:\Users\rod\Desktop\hCaptcha-Bypass-master\main.py", line 49, in new
    driver = Chrome(executable_path="./chromedriver", options=options)
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\webdriver.py", line 168, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

how to fix?

**Comment by MainSilent** [comment]
The chromedriver in repository is for linux and chrome 89, you need to download a chromedriver for the operating system and google chrome version you want to use, that is why at the end it says `is not a valid Win32 application`.
